name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  clang-format:
    name: clang-format style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.18.0
        with:
          clang-format-version: 19
  cmake-format:
    name: cmake-format style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11
          cache: "pip"
      - name: Install lint tool
        run: |
          python -m pip install --upgrade pip
          pip install cmake-format pyyaml
      - name: Check cmake-lint
        run: find . -name CMakeLists.txt | xargs cmake-lint
      - name: Run cmake-format
        run: find . -name CMakeLists.txt | xargs cmake-format -i
      - name: Check cmake-format
        run: git diff --patch-with-stat --exit-code
